services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: development
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      API_PORT: 3000
    volumes:
      - ./backend:/app
